### ISSUE TITLE
Assign domain to SHG

### ISSUE THREAD

**Issue by anunezze** [CIRALabs/Home-Network-Registry-Gateway#5]
As a SHG owner I want my SHG to be assigned a domain name so that it can be accessed from an external client.

Requirements:

- [ ] Add requirement here

Dependencies:
- #20 
- [https://github.com/CIRALabs/SHG-Notes/issues/4](Write spec for DNS)

**Comment by mcr** [comment]
Believed to be done.  Fully verified.
